name: gdgtoulouse
description: Snippets Collection displayed during the meetup.
version: 0.0.1
author: bwnyasse <boris@bwnyasse.net>
homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
